name: qloop-ci

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Smoke demo
        run: qloop run --fixtures fixtures/minute_bars.csv --duration 5 --seed 7 --report-dir out --no-open
      - name: Assert report exists
        run: test -f out/report.html && echo "Report generated"